yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  "@snowpack/plugin-parcel@*":
    dependencies:
      "glob": "*"
      "@babel/plugin-syntax-import-meta": "*"
  "@babel/plugin-syntax-import-meta@*":
    dependencies:
      "@babel/core": "*"